#!/usr/bin/env python3.11


import json
from argparse import Namespace

file_path = 'passwords.json'


def load_passwords() -> list:
    return json.loads(open(file=file_path, mode='r', encoding='UTF-8').read())


def save_new_password(site: str, login: str, password: str):
    passwords = load_passwords()
    passwords.append([site, login, password])
    with open(file=file_path, mode='w', encoding='UTF-8') as file:
        file.write(json.dumps(passwords))
    file.close()


def find_passwords_by_text(text: str):
    passwords = load_passwords()
    result = []
    for password in passwords:
        if text in password[0] or text in password[1] or text in password[2]:
            result.append(password)
    return result


def parse_args() -> Namespace:
    import argparse
    parser = argparse.ArgumentParser(description='Console password drive')
    parser.add_argument('--add', action='store_true')
    parser.add_argument('--site', type=str, help='Site name')
    parser.add_argument('--login', type=str, help='login')
    parser.add_argument('--password', type=str, help='password')
    parser.add_argument('--query', type=str, help='query')
    args = parser.parse_args()
    return args


def cli():
    args = parse_args()
    if args.add:
        if not args.site or not args.login or not args.password:
            print("Specify site, login and password!")
            exit(1)
        save_new_password(args.site, args.login, args.password)
        print("Saved!")
    else:
        if not args.query:
            print("Specify query! Example: passwords --query=ya.ru")
            exit(1)
        print(*find_passwords_by_text(args.query), sep='\n')


if __name__ == '__main__':
    cli()
